// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATudEmEBSuLcUyFb5L8dm-czu-5SoQeh4',
    appId: '1:787480368891:web:5b1ce9ee9ca36f5f3fc25e',
    messagingSenderId: '787480368891',
    projectId: 'crimedispose',
    authDomain: 'crimedispose.firebaseapp.com',
    storageBucket: 'crimedispose.appspot.com',
    measurementId: 'G-BGLTBZ59Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClgcHaf504zBh4IS-ydTEf1dLdtd0MnSs',
    appId: '1:787480368891:android:96d54da2203193ac3fc25e',
    messagingSenderId: '787480368891',
    projectId: 'crimedispose',
    storageBucket: 'crimedispose.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVIKjY7Es8NAgDJrZVR_ikUmilAglWVTo',
    appId: '1:787480368891:ios:4414b0388d8c32af3fc25e',
    messagingSenderId: '787480368891',
    projectId: 'crimedispose',
    storageBucket: 'crimedispose.appspot.com',
    iosBundleId: 'com.example.crimeDispose',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVIKjY7Es8NAgDJrZVR_ikUmilAglWVTo',
    appId: '1:787480368891:ios:ea2d03733eb3283d3fc25e',
    messagingSenderId: '787480368891',
    projectId: 'crimedispose',
    storageBucket: 'crimedispose.appspot.com',
    iosBundleId: 'com.example.crimeDispose.RunnerTests',
  );
}
